### PR TITLE
Add `eventInterval` property for resize and scroll handler

### PR DESCRIPTION
**Pull request by ssutar**
The unified event handler service now accepts additional parameter to configure the event interval with trentmwillis/ember-singularity#25
With this change we are adding a property to mixins which can be overriden in the application if needed

### CODE REVIEW

**Comment by ssutar** [comment]
@trentmwillis These checks are failing on the fresh checkout as well. It just times out for `ember 3.1.0-canary+0e4c3422`

**Comment by stefanpenner** [comment]
@trentmwillis this LGTM, although CI will need to be fixed, what are your thoughts?

**Comment by ssutar** [comment]
@stefanpenner @trentmwillis Can you guys please review again? Looks like the CI errors are fixed with update.

**Comment by stefanpenner** [comment]
released as v2.1.0 🎉

**Pull request merged**
